joyhughes/Jen

Lux/frgb.cpp, Lux/frgb.hpp, Lux/srgb.hpp, frgb.hpp
Extant to do / questions:
still need to test most member functions
still need to add remaining operators (so far only [], <<, and /=)
Syntax for `std::transform()` and related functions
forward reference for `class gamma_lut`
need to learn how to write iterators
Visual Studio shows `std::clamp()` as undefined, but it compiles and runs
=> Add frgb class

Lux/src/frgb.cpp, Lux/src/frgb.hpp
=> Added frgb::end() iterator

Lux/CMakeLists.txt, Lux/src/fimage.cpp, Lux/src/fimage.hpp, Lux/src/frgb.cpp, Lux/src/frgb.hpp, Lux/src/gamma_lut.cpp, Lux/src/gamma_lut.hpp, Lux/src/image.cpp, Lux/src/image.hpp, Lux/src/image_loader.cpp, Lux/src/image_loader.hpp, Lux/src/joy_rand.hpp, Lux/src/linalg.h, Lux/src/lux.cpp, Lux/src/vect2.cpp, Lux/src/vect2.hpp
Add image base class for any kind of rasterized data such as floating point image and vector fields.
Add floating point image derived class fimage and wrappers for loading and writing JPEG and PNG files
Add image testing function in lux.cpp
Add additional functions to frgb and linalg.h
Add descriptive comments to each file
=> Add image class

Lux/CMakeLists.txt, Lux/src/fimage.cpp, Lux/src/fimage.hpp, Lux/src/frgb.cpp, Lux/src/frgb.hpp, Lux/src/image.cpp, Lux/src/image.hpp, Lux/src/image_loader.hpp, Lux/src/joy_rand.hpp, Lux/src/linalg.h, Lux/src/lux.cpp, Lux/src/ucolor.cpp, Lux/src/ucolor.hpp, Lux/src/uimage.cpp, Lux/src/uimage.hpp, Lux/src/vect2.cpp, Lux/src/vect2.hpp, Lux/src/vector_field.cpp, Lux/src/vector_field.hpp, lux.cpp
Add vector field class, testing using `image::warp()`. Bug fixes in `image::sample()` and `struct bounding_box`. General tidying up of code.
=> Add vector field

Lux/CMakeLists.txt, Lux/src/image.cpp, Lux/src/image.hpp, Lux/src/lux.cpp, Lux/src/next_element.hpp, Lux/src/scene.cpp, Lux/src/scene.hpp, Lux/src/vect2.hpp
Add class element containing the parameters for an image splat
Add class cluster to generate a grouping of elements in 2D space
Add functor next_element to recursively generate elements in a cluster
Use std::function to create a vector of component functions - examples: advect_element and scale_ratio
Some code cleanup
---------------------------------------------
Still to do:
More code cleanup & comments
Make component functions more general - be able to apply them to 
Add scene class to load descriptions from files
Add image effect functor
=> Add cluster generation

Lux/CMakeLists.txt, Lux/src/effect.hpp, Lux/src/lux.cpp, Lux/src/vect2.hpp, Lux/src/vector_field.cpp, Lux/src/vector_field.hpp, Lux/src/warp.hpp, image.cpp, image.hpp
Add effect class to run a stack of arbitrary image modifications
Create warp image effect
Test three methods for melting 
- repeatedly apply vector field lookup 
- use integrated vector field with vector field lookup 
- use integrated vector field with calculated function (best result)
=> Add image effects

Lux/CMakeLists.txt, Lux/src/lux.cpp, Lux/src/next_element.cpp, Lux/src/next_element.hpp, Lux/src/scene.cpp, Lux/src/scene.hpp, Lux/src/vect2.cpp, Lux/src/vect2.hpp
Implement a generative function to produce new branches depending on the elements of a current cluster.
=> Add branching clusters

Lux/src/next_element.cpp, Lux/src/next_element.hpp, Lux/src/scene.cpp, Lux/src/scene.hpp
=> Add harness and generalized functions

Lux/src/frgb.cpp, Lux/src/frgb.hpp, Lux/src/image.cpp, Lux/src/image.hpp, Lux/src/lux.cpp, Lux/src/scene.cpp, Lux/src/scene.hpp, Lux/src/ucolor.cpp, Lux/src/ucolor.hpp, Lux/src/vect2.cpp, Lux/src/vect2.hpp, mask_mode.hpp
=> Enable splat with mask, circle crop

Lux/src/fimage.cpp, Lux/src/frgb.cpp, Lux/src/mask_mode.hpp, Lux/src/next_element.cpp, Lux/src/next_element.hpp, Lux/src/scene.hpp, Lux/src/scene_io.cpp, Lux/src/unit_tests.cpp
Fix bug in creating branches on first or second element of cluster. 
New blend modes declared (additive and multiplicative), implementation to follow.
=> Initial derivative of cluster, new blend modes

Lux/src/life.cpp, Lux/src/life.hpp, Lux/src/life_web.cpp
Square four-cell neighborhood, offset on alternate frames. Neighborhood is randomly rotated, producing a diffusion effect.
=> Add Margolis neighborhood

Lux/src/life.cpp, Lux/src/life.hpp, Lux/src/life_web.cpp, Lux/src/ucolor.hpp
Additional rule "gravitate" is still buggy.
=> Add pixel sort CA rule

Lux/src/emscripten.h, Lux/src/fimage.cpp, Lux/src/fimage.hpp, Lux/src/frgb.hpp, Lux/src/image.cpp, Lux/src/image.hpp, Lux/src/palette.hpp, Lux/src/scene.cpp, Lux/src/scene.hpp, Lux/src/ucolor.cpp, Lux/src/ucolor.hpp, Lux/src/uimage.cpp, Lux/src/uimage.hpp, Lux/src/vect2.hpp, Lux/src/vector_field.cpp, Lux/src/vector_field.hpp, Lux/src/warp_field.cpp, Lux/src/warp_field.hpp
Low level functions for color arithmetic, tweaks to rendering functions, generalize scene rendering to any image type
=> Enable uimage render

Lux/samples/curly.json, Lux/samples/galaxy_moon.json, Lux/samples/minimal_function.json, Lux/src/any_function.cpp, Lux/src/any_function.hpp, Lux/src/any_image.hpp, Lux/src/effect.cpp, Lux/src/effect.hpp, Lux/src/hsv.cpp, Lux/src/image.cpp, Lux/src/image.hpp, Lux/src/life.cpp, Lux/src/life.hpp, Lux/src/life_web.cpp, Lux/src/linalg.h, Lux/src/lux.cpp, Lux/src/next_element.cpp, Lux/src/next_element.hpp, Lux/src/offset_field.cpp, Lux/src/offset_field.hpp, Lux/src/scene.cpp, Lux/src/scene.hpp, Lux/src/scene_io.cpp, Lux/src/scene_io.hpp, Lux/src/unit_tests.cpp, Lux/src/vect2.cpp, Lux/src/vect2.hpp, Lux/src/vector_field.cpp, Lux/src/warp_field.hpp
In function tree, use references to functors in std::function. New image types warp_field and offset_field.
=> Modifiable function tree, new image types

Lux/lux_react/src/components/ControlPanel.js, Lux/lux_react/src/components/ImagePortCanvas.js, Lux/lux_react/src/components/MediaController.js, Lux/src/lux_web.cpp, Lux/src/next_element.cpp, Lux/src/scene.cpp, Lux/src/scene.hpp
Make all the buttons in the media controller work - run/pause, advance one frame, and restart
=> Wire up media controller

Lux/lux_react/src/components/ImagePortCanvas.js, Lux/src/lux_web.cpp, Lux/src/vect2.hpp
This brings the React app up to the same level of functionality as the former HTML app.
=> Add react mouse interaction

Lux/lux_react/src/components/ControlPanel.js, Lux/src/buffer_pair.cpp, Lux/src/buffer_pair.hpp, Lux/src/lux_web.cpp, Lux/src/next_element.cpp, Lux/src/scene.hpp
Slider range, default value, step, and label set from C++ via Emscripten. Tooltips still need work.
=> Set slider props from c++

Lux/lux_react/src/components/ControlPanel.js, Lux/src/lux_web.cpp
A small change in slider look and feel. Slider label is moved to above. Value label is removed, replaced with an input field to the right.
=> Add input to slider

Lux/lux_react/src/components/ControlPanel.js, Lux/lux_react/src/components/JenMenu.js, Lux/lux_react/src/components/JenSlider.js, Lux/lux_react/src/components/MediaController.js, Lux/src/lux_web.cpp
Create function components JenSlider and JenMenu
Add tooltips with description when hovering over label
Move container into MediaController
=> Seperate UI components for slider and menu

Lux/lux_react/src/components/JenMenu.js, Lux/lux_react/src/components/JenSlider.js
Place an info icon in upper right of widget container. Tooltip on hover or touch on icon.
=> Move tooltip to upper right of container

Lux/lux_react/src/components/ControlPanel.js, Lux/lux_react/src/components/ImagePortCanvas.js, Lux/lux_react/src/components/JenMenu.js, Lux/lux_react/src/components/JenSlider.js, Lux/lux_react/src/components/JenSwitch.js, Lux/lux_react/src/components/WidgetGroup.js, Lux/nebula_files/CA_choices.json, Lux/nebula_files/CA_test.json, Lux/nebula_files/nebula_brush.json, Lux/nebula_files/test_widgets.json, Lux/src/UI.cpp, Lux/src/UI.hpp, Lux/src/any_function.hpp, Lux/src/effect.cpp, Lux/src/joy_concepts.hpp, Lux/src/joy_rand.hpp, Lux/src/life.cpp, Lux/src/life.hpp, Lux/src/lux_web.cpp, Lux/src/next_element.cpp, Lux/src/next_element.hpp, Lux/src/scene.cpp, Lux/src/scene.hpp, Lux/src/scene_io.cpp, Lux/src/scene_io.hpp
Generate UI from JSON passed from C++ via Emscripten. Currently a hand written JSON segment is used. Next up - generate the JSON automatically.
=> Pass json for UI

Lux/nebula_files/CA_choices.json, Lux/src/UI.cpp, Lux/src/UI.hpp, Lux/src/any_function.hpp, Lux/src/next_element.cpp, Lux/src/next_element.hpp, Lux/src/scene_io.cpp
Add widget groups from scene file to UI object in scene
Create equal condition functions
No changes visible to a hypothetical user
=> Load widget groups

Lux/lux_react/src/components/JenSlider.js, Lux/lux_react/src/components/JenSwitch.js, Lux/lux_react/src/components/WidgetGroup.js, Lux/nebula_files/CA_choices.json, Lux/nebula_files/test_widgets.json, Lux/src/life.cpp, Lux/src/lux_web.cpp
Switch container is narrower than that of other components
=> Add switch widget

Lux/lux_react/src/components/JenSlider.js, Lux/lux_react/src/components/JenSwitch.js, Lux/lux_react/src/components/WidgetGroup.js, Lux/nebula_files/CA_choices.json, Lux/nebula_files/test_widgets.json, Lux/src/UI.hpp, Lux/src/joy_rand.hpp, Lux/src/life.cpp, Lux/src/life.hpp, Lux/src/lux_web.cpp, Lux/src/next_element.cpp, Lux/src/scene_io.cpp, Lux/src/scene_io.hpp
Not entirely satisfied with the design. Number input box to the right binds to the thumb most recently clicked. Other options include adding an indicator such as an arrow showing if it is max or min in the box, adding a second input, or using numbers hovering over the slider.
=> Add range slider

Lux/lux_react/src/components/JenDirection4.js, Lux/lux_react/src/components/JenDirection8.js, Lux/lux_react/src/components/WidgetGroup.js, Lux/nebula_files/CA_choices.json, Lux/nebula_files/test_widgets.json, Lux/src/life.cpp, Lux/src/lux_web.cpp
Add tools to allow user to choose a direction4 or direction8, using a grid of buttons with arrow icons.
Fix gravity and snow rules to respond correctly to direction change.
=> Add direction pickers

Lux/lux_react/src/components/WidgetGroup.js, Lux/src/UI.cpp, Lux/src/UI.hpp, Lux/src/any_function.hpp, Lux/src/lux_web.cpp, Lux/src/scene.hpp, Lux/src/scene_io.cpp, Lux/src/scene_io.hpp
Changes to scene data - all function types now unified in a single namespace. Type any_function is a variant including any_fn< T >, gen_fn, and condition_fn.
=> Write sample json from scene

Lux/lux_react/src/components/ControlPanel.js, Lux/lux_react/src/components/JenDirection4.js, Lux/lux_react/src/components/JenDirection8.js, Lux/lux_react/src/components/JenMenu.js, Lux/lux_react/src/components/JenSwitch.js, Lux/lux_react/src/components/WidgetGroup.js, Lux/nebula_files/CA_choices.json, Lux/src/UI.cpp, Lux/src/UI.hpp, Lux/src/lux_web.cpp, Lux/src/scene.hpp, Lux/src/scene_io.cpp, Lux/src/scene_io.hpp
Flexible UI with components that change with menu choice, generated from the scene file.
=> Generate UI json from scene

Lux/src/fimage.cpp, Lux/src/frgb.cpp, Lux/src/frgb.hpp, Lux/src/image.cpp, Lux/src/image.hpp, Lux/src/scene.cpp, Lux/src/scene.hpp, Lux/src/scene_io.cpp, Lux/src/ucolor.cpp, Lux/src/ucolor.hpp, Lux/src/uimage.cpp, Lux/src/uimage.hpp, Lux/src/vect2.hpp, Lux/src/vector_field.cpp
Mip-mapping implemented but currently in debugging phase. It has been disabled while I am in project management mode.
=> WIP add mip map

.gitignore, Lux/lux_react/src/components/ControlPanel.js, Lux/lux_react/src/components/InterfaceContainer.js, Lux/lux_react/src/pages/Home.js, package-lock.json
=> Scrolling Bug Solved

Lux/lux_react/src/components/JenBlurPicker.js, Lux/nebula_files/CA_choices.json
Make box blur variant CAs easier to use by separating into "Box Blur" and "Blurriffic"
=> Separate box blur and custom blur

Lux/lux_react/src/components/WidgetGroup.js
Make code less repetitious (DRY principle)
=> Add JSX for widget label and description

CMakeLists.txt, Lux/CMakeLists.txt, Lux/src/image_test.cpp, Lux/src/scene_io.hpp
It's been a while since I've run Lux on the command line so I updated and tested to make sure it still works.
=> Fix lux command line build

Jen-C/README.md, Lux/LICENSE.md, Lux/README.md, niffer/README.md
I will add license and deprecation notices as appropriate to each file shortly.
=> Add mit license, note deprecations

.github/workflows/build.yaml, Dockerfile, build-docker-image, run-build-test, rund
=> Run cicd test 02

CONTRIBUTING.md
Merged different version submitted. Add request to "star" this repo and link to video.
=> Merge contributing.md

.github/workflows/build.yaml, Lux/Makefile, Lux/src/any_rule.hpp, Lux/src/image.cpp, Lux/src/image.hpp, Lux/src/scene.cpp, run-emscripten-build-test
add emscripten build test to cicd
=> add emscripten build test

Lux/README.md, README.md
- Added link and also a screenshot 
- Centered the images
- Fixed a few typos as well
Closes #119
Let me know if you decide to create LEARN.md!
=> docs: Add Joyographic react app demo to README.md

.github/workloads/auto-comment-on-pr-merge.yml
=> Added the feature to auto comment on pr merged

Lux/lux_react/package-lock.json, Lux/lux_react/package.json
Should fix last dependabot security issue
=> Update @adobe/css-tools to version 4.4.0

Lux/nebula_files/CA_choices.json, Lux/nebula_files/kaleido.json, Lux/src/any_function.hpp, Lux/src/effect.cpp, Lux/src/effect.hpp, Lux/src/lux_web.cpp, Lux/src/next_element.cpp, Lux/src/next_element.hpp, Lux/src/scene_io.cpp, Lux/src/vector_field.cpp, Lux/src/vector_field.hpp
Adding a second scene file to the mix. Generates kaleidoscope patterns. More will be added to this scene file later.
=> Initial kaleidoscope scene file

Lux/lux_react/package-lock.json, Lux/lux_react/package.json, Lux/lux_react/src/components/ControlPanel.jsx, Lux/lux_react/src/components/InterfaceContainer.jsx, Lux/lux_react/src/components/MasonryImagePicker.css, Lux/lux_react/src/components/MasonryImagePicker.jsx, Lux/lux_react/src/components/TabNavigation.jsx, Lux/lux_react/src/components/panes/BrushPane.jsx, Lux/lux_react/src/components/panes/HomePane.jsx, Lux/lux_react/src/components/panes/SourceImagePane.jsx, Lux/lux_react/src/components/panes/TargetImagePane.jsx, Lux/lux_react/src/pages/Home.jsx
- Created TabNavigation component with Home, Source, Target and Brush tabs
- Implemented empty pane components for each tab section
- Added tab switching logic to display content based on selected tab
- Reorganized control panel layout for better space management
- Improved responsive behavior for both desktop and mobile views
- Maintained compatibility with existing widget system
=> Implement tabbed navigation system for improved UI organization

Lux/ControlPanel.js, Lux/lux_react/package-lock.json, Lux/lux_react/package.json, Lux/lux_react/src/components/ControlPanel.jsx, Lux/lux_react/src/components/ImagePort.jsx, Lux/lux_react/src/components/InterfaceContainer.jsx, Lux/lux_react/src/components/JenSwitch.jsx, Lux/lux_react/src/components/MasonryImagePicker.css, Lux/lux_react/src/components/MasonryImagePicker.jsx, Lux/lux_react/src/components/MediaController.jsx, Lux/lux_react/src/components/TabNavigation.jsx, Lux/lux_react/src/components/ThumbnailItem.jsx, Lux/lux_react/src/components/WidgetGroup.jsx, Lux/lux_react/src/components/panes/BrushPane.jsx, Lux/lux_react/src/components/panes/HomePane.jsx, Lux/lux_react/src/components/panes/SourceImagePane.jsx, Lux/lux_react/src/components/panes/TargetImagePane.jsx, Lux/lux_react/src/pages/Home.jsx
1. Replaced the dropdown-based image selector with a responsive thumbnail grid
2. Enhanced the ThumbnailItem component with better error handling and debugging
3. Implemented drag-and-drop image upload functionality
4. Added visual indicators for selected images and loading states
5. Fixed issues with images not displaying in the Source Image pane
=> Implemented Masonry Grid for Source Image Pane with Thumbnails

Lux/lux_files/CA_choices.json, Lux/lux_files/hue.json, Lux/lux_react/src/components/ControlPanel.jsx, Lux/lux_react/src/components/ImagePort.jsx, Lux/lux_react/src/components/JenMenu.jsx, Lux/lux_react/src/components/JenSlider.jsx, Lux/lux_react/src/components/MediaController.jsx, Lux/lux_react/src/components/WidgetGroup.jsx, Lux/lux_react/src/components/panes/HomePane.jsx, Lux/lux_react/src/components/panes/SceneChooserPane.jsx
* Fix font inconsistency issue in the pull-down menu
* Resolve loading image on different environments 
* Make the full-screen bottom to the bottom left of the image port
* Fix widgets load properly when changing scenes
* Adding some missing widget backs to the scene
=> Update the Jen components using consistent font family

Lux/lux_react/src/components/ControlPanel.jsx, Lux/lux_react/src/components/InterfaceContainer.jsx, Lux/lux_react/src/components/MediaController.jsx, Lux/lux_react/src/components/panes/PaneContext.jsx, Lux/lux_react/src/components/panes/SceneChooserPane.jsx
Switch home pane on scene change
=> Switch home pane on scene change

Lux/lux_files/bit_plane.json, Lux/lux_files/scenes.json, Lux/lux_react/src/components/JenColorPicker.jsx, Lux/lux_react/src/components/JenFunkyPicker.jsx, Lux/lux_react/src/components/WidgetGroup.jsx, Lux/src/UI.cpp, Lux/src/UI.hpp, Lux/src/any_effect.hpp, Lux/src/any_function.hpp, Lux/src/effect.cpp, Lux/src/effect.hpp, Lux/src/image.cpp, Lux/src/image.hpp, Lux/src/lux_web.cpp, Lux/src/scene_io.cpp, Lux/src/ucolor.hpp, Lux/src/uimage.cpp, Lux/src/uimage.hpp
=> Bit plane effect and bitwise color picker

Lux/lux_react/src/components/WidgetGroup.jsx, Lux/lux_react/src/components/panes/HomePane.jsx
Widgets are no longer forced into groups but flow separately within the masonry
=> Allow widgets to flow separately within home pane

Lux/lux_files/hue.json, Lux/src/lux_web.cpp
Remove code forcing kaleidoscope scene
We need to make sure that backend code does not look for specific scenes.
=> Add live camera to hues scene

Lux/lux_files/CA_choices.json, Lux/lux_react/src/components/panes/HomePane.jsx, Lux/src/life.cpp, Lux/src/life.hpp, Lux/src/lux_web.cpp, Lux/src/scene_io.cpp, Lux/stb_image/stb_image.h, Lux/stb_image/stb_image_write.h
For the moment a pull down menu is used for target image - later we will use target pane
Targeting will only work if target image has same dimensions as source. If not, a message is printed to console but no error is thrown.
=> Cellular automata targeting

Lux/lux_files/kaleido.json
Moved audio functions lower in scene file - Forward references not allowed in scene files
=> Fix spin and expand sliders

Lux/lux_files/CA_choices.json, Lux/lux_files/kaleido.json, Lux/src/any_function.hpp, Lux/src/next_element.hpp, Lux/src/scene_io.cpp
Fix autoplay sensitivity in kaleido and CA scenes
=> Improved error handling for scene_reader

.gitattributes, Lux/lux_files/posterize.json, Lux/lux_files/scenes.json, Lux/src/any_effect.hpp, Lux/src/effect.cpp, Lux/src/effect.hpp, Lux/src/image.hpp, Lux/src/lux_web.cpp, Lux/src/scene_io.cpp, Lux/src/ucolor.hpp, Lux/src/uimage.cpp, Lux/src/uimage.hpp
Resulting color palette is not great but I want to keep this in the flow
=> Hsv color effects
